-- CreateTable
CREATE TABLE "Match" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "mode" TEXT NOT NULL DEFAULT 'Solos',
    "placement" INTEGER NOT NULL,
    "kills" INTEGER NOT NULL DEFAULT 0,
    "assists" INTEGER NOT NULL DEFAULT 0,
    "survived" INTEGER NOT NULL DEFAULT 0,
    "tilt" INTEGER NOT NULL DEFAULT 5,
    "mood" TEXT NOT NULL DEFAULT 'neutral',
    "notes" TEXT NOT NULL DEFAULT '',
    "win" BOOLEAN NOT NULL DEFAULT false
);
